name: build690-msvc

on: workflow_dispatch

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2019

    steps:
    - name: Download Qt Everywhere
      uses: actions/checkout@v4
      
    - name: Install Python 3.13.2 version
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'
        architecture: 'x64'
        
    - name: Download Qt source
      run: |
        # Download qt-everywhere-src-6.9.0.zip
        curl -L -o qt-everywhere-src-6.9.0.zip https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.zip
        # Extract qt-everywhere-src-6.9.0.zip
        7z x qt-everywhere-src-6.9.0.zip

    - name: Cache Qt build
      uses: actions/cache@v4
      with:
        path: |
          ./qt-everywhere-src-6.9.0
        key: ${{ runner.os }}-qt-everywhere-src-6.9.0
        restore-keys: |
          ${{ runner.os }}-qt

    - name: Qt build
      run: |
        # Setup the compiler
        cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
        Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
        # Configure Qt6
        mkdir qt6_shadow
        cd qt6_shadow
        ..\qt-everywhere-src-6.9.0\configure.bat -static -static-runtime -no-pch -optimize-size -platform win32-msvc -prefix "..\qt6_690_static_64" -opensource -confirm-license -release -nomake examples -nomake tests
        cmake --build . --parallel 4
        cmake --install .
        
    - uses: actions/upload-artifact@v4
      with:
        name: qt6_690_static_64
        path: qt6_690_static_64
