name: build690-mingw

on: workflow_dispatch

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Python 3.13.2 
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2 '
        architecture: 'x64'
        
    - name: Install MSYS2 (includes MinGW)
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          unzip

    - name: Download Qt source
      run: |
        curl -L -o qt-everywhere-src-6.9.0.zip https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.zip
        7z x qt-everywhere-src-6.9.0.zip

    - name: Cache Qt build
      uses: actions/cache@v4
      with:
        path: |
          ./qt-everywhere-src-6.9.0
        key: ${{ runner.os }}-qt-everywhere-src-6.9.0-mingw
        restore-keys: |
          ${{ runner.os }}-qt

    - name: Configure and Build Qt with MinGW
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        mkdir qt6_shadow
        cd qt6_shadow
        ../qt-everywhere-src-6.9.0/configure -prefix ../qt6_690_static_mingw64 -static -static-runtime -release -opensource -confirm-license -nomake tests -nomake examples -platform win32-g++ -optimize-size -no-pch
        make -j$(nproc)
        make install

    - name: Upload static Qt6 artifact
      uses: actions/upload-artifact@v4
      with:
        name: qt6_690_static_mingw64
        path: qt6_690_static_mingw64
